project_id = "giohtapleewzetffgnnz"

[functions.generate-tour]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.auto-blog-publisher]
verify_jwt = false
